version: 0.2

phases:
  build:
    commands:
      - echo "Running build"
      - npm install
      - npm test
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
